### ISSUE TITLE
Handling for NAs

### ISSUE THREAD

**Issue by trinker** [bmewing/mgsub#2]
Nice work here.  I see that the package now handles vectors.  👏 

It throws an error if the string vector passed contains a missing value.  Could you add handling for this:

```
x <- c(NA, 'this is good', 'this is not')
subs <- c('is', 'this')
replaces <- as.list(c('IS', 'THIS'))

names(replaces) <- subs

mgsub(x, replaces)
## Error in while (nchar(s) > 0) { : missing value where TRUE/FALSE needed
```

**Comment by trinker** [comment]
Required for #2: https://github.com/bmewing/mgsub/issues/2

**Comment by bmewing** [comment]
Wow - sorry, Outlook decided that emails from github were 'clutter'...ugh. Will investigate this immediately.

**Comment by bmewing** [comment]
I believe I have fixed this now.

**Comment by bmewing** [comment]
#4
