### ISSUE TITLE
Reconsider explicitly naming the arguments to mgsub (subs and replacementspassed via ldots)

### ISSUE THREAD

**Issue by trinker** [bmewing/mgsub#3]
I'd argue for naming the arguments: pattern,replacement.  This makes it explicit what the function does without the need for documentation.  Also it allows for a nicer interface when used in RStudio as the arguments are displayed when the function name is typed in.

**Comment by trinker** [comment]
A quick search of the rpo reveals this is in the README.  A few lines before that is:

```
if (!require("pacman")) install.packages("pacman")
pacman::p_load_gh("trinker/sentimentr", "trinker/stansent", "sfeuerriegel/SentimentAnalysis", "wrathematics/meanr")
pacman::p_load(syuzhet, qdap, microbenchmark, RSentiment)
```

This installs qdap which has the `left_just` function.  Did you run this?  If you did, qdap is either loaded or the `p_load` threw a warning or error. The  In any event we need more information to debug this.

**Comment by bmewing** [comment]
Updated dev today with a fix for this. I deprecated the named list (dictionary) approach from being supported in the main `mgsub` call (though it is still available as `mgsub_dict` and `mgsub` handles those types of calls with a warning. In another release to CRAN or so, I'll drop it from mgsub entirely.

**Comment by bmewing** [comment]
#4
